name: Feature Request
description: Suggest an idea for a brand new feature, or a change to an existing one.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for your suggestion!

        We welcome any ideas about how to make **NWB Widgets** better for the community.

        Please keep in mind that new features may not get implemented immediately.
  - type: textarea
    id: summary
    attributes:
      label: What would you like to see added to NWB Widgets?
    validations:
      required: true
  - type: dropdown
    id: interest
    attributes:
      label: Do you have any interest in helping implement the feature?
      description: |
        We appreciate any help you can offer!

        For information on how to contribute, please refer to our [developer guide](https://nwb-widgets.readthedocs.io/en/latest/contents/developer_guide.html).
      options:
        - Yes.
        - Yes, but I would need guidance.
        - No.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbwidgets/blob/master/.github/CODE_OF_CONDUCT.rst)
          required: true
        - label: Have you ensured this feature was not already [requested](https://github.com/NeurodataWithoutBorders/nwbwidgets/issues)?
          required: true
