FROM python:3.10

COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install -r requirements.txt \
    && pip install nwbwidgets

WORKDIR /app
RUN mkdir local_files
RUN mkdir nwb-cache

COPY favicon.ico .
COPY NWB_Panel.ipynb .
COPY run.sh .

EXPOSE 8866
CMD ["./run.sh"]
